---
apiVersion: v1
kind: Service
metadata:
  name: flight-dynamic-service
  namespace: srinu
spec:
  type: LoadBalancer
  selector:
    app: flight-dynamic
  ports:
  - protocol: TCP
    port: 80          # External port accessible by users
    targetPort: 8080  # Directs traffic to container port 8080
